name: Call Generate Release Note

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch for the pull request'
        required: true
        default: 'main'
  pull_request:

jobs:
  call-generate-release-note:
    uses: NRLMMD-GEOIPS/.github/.github/workflows/generate-release-note.yaml{19-add-brassy-builds-on-tag-to-ci}
    with:
      base_branch: ${{ github.event.inputs.base_branch }}
      github_token: ${{ secrets.GITHUB_TOKEN }}

